export enum PlayTypes {
	EndPeriod = 2,
	PassIncompletion = 3,
	Rush = 5,
	Sack = 7,
	KickoffReturn = 12,
	Timeout = 21,
	PassReception = 24,
	PassInterceptionReturn = 26,
	FumbleRecoveryOpponent = 29,
	Punt = 52,
	Kickoff = 53,
	FieldGoalGood = 59,
	FieldGoalMissed = 60,
	EndofHalf = 65,
	EndofGame = 66,
	PassingTouchdown = 67,
	RushingTouchdown = 68,
	OfficalTimeout = 74,
	TwoMinuteWarning = 75
}
